language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y --allow-unauthenticated software-properties-common ffmpeg

script:
  - phpunit
