language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
      env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-stable'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*' COMPOSER_FLAGS='--prefer-stable'
  fast_finish: true

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - composer config discard-changes true
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest
  - sudo add-apt-repository -y ppa:mc3man/xerus-media
  - sudo apt-get -qq update
  - sudo apt-get install -y --allow-unauthenticated software-properties-common ffmpeg

script:
  - vendor/bin/phpunit